spring:
  data:
    mongodb:
      host: ${MYSQL_DB_HOSTNAME}
      port: 27017
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      database: users
      authentication-database: admin

server:
  port: 8080
